[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
function get_flush(hand)
  local ret = {}
  local four_fingers = next(find_joker('Four Fingers'))
  local suits = SMODS.Suit.obj_buffer
  if #hand < (5 - (four_fingers and 1 or 0)) then return ret else
'''
position = "at"
payload = '''
function get_flush(hand)
  local ret = {}
  local four_fingers = next(find_joker('Four Fingers'))
  local envido = next(SMODS.find_card('j_spdeck_envido'))
  local suits = SMODS.Suit.obj_buffer
  if #hand < (5 - (four_fingers and 1 or envido and 3 or 0 )) then return ret else
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
if flush_count >= (5 - (four_fingers and 1 or 0)) then
'''
position = "at"
payload = '''
if flush_count >= (5 - (four_fingers and 1 or 0)) or flush_count == (envido and 2) then
'''
match_indent = true
times = 1